import { useCallback, useEffect, useRef, useState } from "react";
import { BatteryCharging, CaretDown, CaretLeft, CaretRight, CaretUp, CheckCircle, CircleNotch, Clock, Cpu, Gauge, Info, LockKey, Engine, Play, Power, SlidersHorizontal, Speedometer, StopCircle, TerminalWindow, Thermometer, Warning, WifiHigh } from "@phosphor-icons/react";

const API="/api", CLIENT_ID=`webui-${Math.random().toString(16).slice(2,8)}`;
const JOYSTICK_DEADZONE=0.08, MAX_LINEAR=0.6, MAX_ANGULAR=2.0;
const initial={service_online:false,simulation:true,can_interface:"can0",can_state:"unknown",control:{owned:false},drive:{enabled:false,emergency_stop:false,soft_stopping:false,linear_m_s:0,angular_rad_s:0,target_linear_m_s:0,target_angular_rad_s:0},motors:{left:{id:1,online:false,velocity_rad_s:0,bus_voltage_v:0,motor_temperature_c:0},right:{id:2,online:false,velocity_rad_s:0,bus_voltage_v:0,motor_temperature_c:0}},updated_at:"--"};
async function api(path,options={}){const r=await fetch(`${API}${path}`,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`请求失败 (${r.status})`);return p}
function applyDeadzone(value,deadzone=JOYSTICK_DEADZONE){const magnitude=Math.abs(value);if(magnitude<=deadzone)return 0;return Math.sign(value)*((magnitude-deadzone)/(1-deadzone))}
function NavItem({icon:Icon,label,active}){return <button className={`nav-item ${active?"active":""}`}><Icon size={23} weight={active?"duotone":"regular"}/><span>{label}</span></button>}
function StatusLine({children,tone="cyan"}){return <span className={`status-line ${tone}`}><i/>{children}</span>}
function DataRow({icon:Icon,label,left,right,suffix=""}){return <div className="data-row"><div className="row-label"><Icon size={24}/><span>{label}</span></div><strong>{left}{suffix}</strong><strong>{right}{suffix}</strong></div>}
function Joystick({disabled,onVector,onEngage,onRelease}){const ref=useRef(null);const [knob,setKnob]=useState({x:0,y:0});const move=useCallback(e=>{if(disabled||!ref.current)return;const rect=ref.current.getBoundingClientRect(),radius=rect.width/2-30;let x=e.clientX-(rect.left+rect.width/2),y=e.clientY-(rect.top+rect.height/2),d=Math.hypot(x,y);if(d>radius){x*=radius/d;y*=radius/d}setKnob({x,y});const rawLinear=Math.max(-1,Math.min(1,-y/radius)),rawAngular=Math.max(-1,Math.min(1,x/radius));onVector({linear:applyDeadzone(rawLinear),angular:applyDeadzone(rawAngular)})},[disabled,onVector]);const release=useCallback(e=>{if(ref.current?.hasPointerCapture(e.pointerId))ref.current.releasePointerCapture(e.pointerId);setKnob({x:0,y:0});onRelease()},[onRelease]);return <div ref={ref} className={`joystick ${disabled?"disabled":""}`} role="slider" aria-label="底盘速度摇杆" aria-disabled={disabled} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);onEngage();move(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))move(e)}} onPointerUp={release} onPointerCancel={release}><span className="cross x"/><span className="cross y"/><span className="circle c1"/><span className="circle c2"/><b className="dir n">前进<small>+0.60 m/s</small></b><b className="dir s">后退<small>-0.60 m/s</small></b><b className="dir w">左转<small>-2.0 rad/s</small></b><b className="dir e">右转<small>+2.0 rad/s</small></b><CaretUp className="arrow a-n"/><CaretDown className="arrow a-s"/><CaretLeft className="arrow a-w"/><CaretRight className="arrow a-e"/><div className="knob" style={{transform:`translate(${knob.x}px,${knob.y}px)`}}><span/></div></div>}

export function App(){
 const [state,setState]=useState(initial),[events,setEvents]=useState([]),[token,setToken]=useState(()=>sessionStorage.getItem("chassis-token")||""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [vector,setVector]=useState({linear:0,angular:0}),[deadman,setDeadman]=useState(false);const keyRef=useRef(new Set()),engageRef=useRef(0),vectorRef=useRef({linear:0,angular:0}),deadmanRef=useRef(false);
 const refresh=useCallback(async()=>{try{setState(await api("/state",{headers:token?{"X-Control-Token":token}:{}}));setError("")}catch(e){setState(s=>({...s,service_online:false,can_state:"disconnected"}));setError(e.message)}},[token]);
 const refreshEvents=useCallback(async()=>{try{setEvents((await api("/events")).events||[])}catch{}},[]);
 useEffect(()=>{refresh();refreshEvents();const a=setInterval(refresh,500),b=setInterval(refreshEvents,1500);return()=>{clearInterval(a);clearInterval(b)}},[refresh,refreshEvents]);
 const act=async fn=>{setBusy(true);setError("");try{await fn();await refresh();await refreshEvents()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const acquire=()=>act(async()=>{const p=await api("/control/acquire",{method:"POST",body:JSON.stringify({owner:CLIENT_ID})});sessionStorage.setItem("chassis-token",p.token);setToken(p.token)});
 const release=()=>act(async()=>{await api("/control/release",{method:"POST",body:JSON.stringify({token})});sessionStorage.removeItem("chassis-token");setToken("")});
 const postVector=useCallback(async v=>api("/drive/command",{method:"POST",body:JSON.stringify({token,linear:v.linear*MAX_LINEAR,angular:v.angular*MAX_ANGULAR})}),[token]);
 const send=useCallback(async v=>{vectorRef.current=v;setVector(v);if(!token||!deadmanRef.current||state.drive.emergency_stop)return;try{await postVector(v)}catch(e){setError(e.message)}},[token,state.drive.emergency_stop,postVector]);
 const stop=useCallback(async()=>{const zero={linear:0,angular:0};vectorRef.current=zero;setVector(zero);if(token)try{await api("/drive/stop",{method:"POST",body:JSON.stringify({token})})}catch(e){setError(e.message)}},[token]);
 const deadmanStart=async()=>{if(!token||state.drive.emergency_stop||deadmanRef.current)return;const generation=++engageRef.current;try{await api("/drive/enable",{method:"POST",body:JSON.stringify({token})});if(engageRef.current!==generation)return;deadmanRef.current=true;setDeadman(true);await postVector(vectorRef.current)}catch(e){if(engageRef.current===generation){deadmanRef.current=false;setDeadman(false)}setError(e.message)}};
 const deadmanStop=useCallback(async()=>{engageRef.current+=1;deadmanRef.current=false;setDeadman(false);if(token)try{await api("/drive/disable",{method:"POST",body:JSON.stringify({token})})}catch(e){setError(e.message)}},[token]);
 const joystickRelease=useCallback(async()=>{await stop();await deadmanStop()},[stop,deadmanStop]);
 useEffect(()=>{if(!deadman||!token)return;const t=setInterval(()=>postVector(vectorRef.current).catch(e=>setError(e.message)),100);return()=>clearInterval(t)},[deadman,token,postVector]);
 useEffect(()=>{const get=()=>({linear:(keyRef.current.has("w")||keyRef.current.has("arrowup")?1:0)-(keyRef.current.has("s")||keyRef.current.has("arrowdown")?1:0),angular:(keyRef.current.has("d")||keyRef.current.has("arrowright")?1:0)-(keyRef.current.has("a")||keyRef.current.has("arrowleft")?1:0)});const down=e=>{const k=e.key.toLowerCase();if(k===" "){e.preventDefault();if(!deadman)deadmanStart();return}if(!["w","a","s","d","arrowup","arrowdown","arrowleft","arrowright"].includes(k))return;e.preventDefault();keyRef.current.add(k);send(get())};const up=e=>{const k=e.key.toLowerCase();if(k===" "){deadmanStop();return}keyRef.current.delete(k);send(get())};addEventListener("keydown",down);addEventListener("keyup",up);addEventListener("blur",deadmanStop);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up);removeEventListener("blur",deadmanStop)}},[deadman,send,deadmanStop]);
 const owned=Boolean(token&&state.control.owned),ready=owned&&!state.drive.emergency_stop,left=state.motors.left,right=state.motors.right;
 const linear=Number(state.drive.linear_m_s||0).toFixed(2),angular=Number(state.drive.angular_rad_s||0).toFixed(2);
 const targetLinear=Number(state.drive.target_linear_m_s||0).toFixed(2),targetAngular=Number(state.drive.target_angular_rad_s||0).toFixed(2);
 return <>
  <aside><div className="brand"><div className="logo"/><div><strong>DM-H65</strong><span>双轮底盘调试台</span></div></div><nav><NavItem icon={Gauge} label="实时控制" active/><NavItem icon={SlidersHorizontal} label="电机参数"/><NavItem icon={TerminalWindow} label="诊断日志"/><NavItem icon={Info} label="帮助说明"/></nav><div className="aside-foot"><WifiHigh size={18}/><span>{state.can_state==="up"?"CAN 链路正常":"CAN 链路异常"}</span></div></aside>
  <main><header><StatusLine tone="green">服务在线</StatusLine><span className="separator"/><StatusLine>CAN0 · 1 Mbps</StatusLine><span className="separator"/><button className={`control-lock ${owned?"owned":""}`} onClick={owned?release:acquire} disabled={busy||!state.service_online}>{busy?<CircleNotch className="spin"/>:<LockKey size={25}/>} {owned?"控制权已锁定":"取得控制权"}</button><button className="estop" onClick={()=>act(()=>api("/drive/emergency-stop",{method:"POST",body:"{}"}))}><StopCircle size={31} weight="bold"/>急停</button></header>
   {error&&<div className="error"><Warning size={18}/>{error}</div>}
   {state.drive.emergency_stop&&<div className="error"><StopCircle size={18}/>急停已锁定，电机输出被禁止。<button disabled={!owned} onClick={()=>act(()=>api("/drive/reset-emergency",{method:"POST",body:JSON.stringify({token})}))}>确认安全并复位</button></div>}
   {state.drive.soft_stopping&&<div className="error"><Clock size={18}/>正在平滑停车，输出会先减速到零，再切断使能。</div>}
   <section className="console-grid">
    <article className="panel joystick-panel"><div className="panel-head"><div><h2>底盘速度控制</h2><p>按住摇杆自动使能；松手后先平滑减速，再关闭输出。</p></div><StatusLine tone={deadman?"green":"cyan"}>{deadman?"输出已使能":"待命"}</StatusLine></div><Joystick disabled={!ready} onVector={send} onEngage={deadmanStart} onRelease={joystickRelease}/><div className="vector-readout"><div><span>目标线速度</span><strong>{(vector.linear*MAX_LINEAR).toFixed(2)} m/s</strong></div><div><span>目标角速度</span><strong>{(vector.angular*MAX_ANGULAR).toFixed(2)} rad/s</strong></div><div><span>输出线速度</span><strong>{linear} m/s</strong></div><div><span>输出角速度</span><strong>{angular} rad/s</strong></div></div><div className="hint-row"><span>死区 {Math.round(JOYSTICK_DEADZONE*100)}%</span><span>服务端斜坡 0.6 m/s² · 1.5 rad/s²</span><span>目标 {targetLinear}/{targetAngular}</span></div></article>
    <article className="panel telemetry-panel"><div className="panel-head"><div><h2>电机遥测</h2><p>左右轮实时状态</p></div><StatusLine tone={left.online&&right.online?"green":"cyan"}>{left.online&&right.online?"双电机在线":"等待反馈"}</StatusLine></div>
     <div className="motor-grid"><div className="motor-card"><h3>左轮 · ID 1</h3><DataRow icon={Speedometer} label="速度" left={Number(left.velocity_rad_s||0).toFixed(2)} right="" suffix=" rad/s"/><DataRow icon={BatteryCharging} label="母线电压" left={Number(left.bus_voltage_v||0).toFixed(1)} right="" suffix=" V"/><DataRow icon={Thermometer} label="电机温度" left={Number(left.motor_temperature_c||0).toFixed(1)} right="" suffix=" °C"/></div><div className="motor-card"><h3>右轮 · ID 2</h3><DataRow icon={Speedometer} label="速度" left={Number(right.velocity_rad_s||0).toFixed(2)} right="" suffix=" rad/s"/><DataRow icon={BatteryCharging} label="母线电压" left={Number(right.bus_voltage_v||0).toFixed(1)} right="" suffix=" V"/><DataRow icon={Thermometer} label="电机温度" left={Number(right.motor_temperature_c||0).toFixed(1)} right="" suffix=" °C"/></div></div>
     <div className="event-list">{events.slice(0,6).map((item,index)=><div key={`${item.time}-${index}`} className={`event ${item.level||"info"}`}><Clock size={16}/><span>{item.time}</span><strong>{item.message}</strong></div>)}</div>
    </article>
   </section>
   <footer><div><Engine size={18}/><span>模拟模式：{state.simulation?"开启":"关闭"}</span></div><div><Cpu size={18}/><span>更新于 {state.updated_at}</span></div><div><Play size={18}/><span>空格键死人和键盘 WASD 可用</span></div><div><Power size={18}/><span>{owned?"已持有控制权":"未持有控制权"}</span></div></footer>
  </main>
 </>
}
