import { useCallback, useEffect, useRef, useState } from "react";
import { BatteryCharging, CaretDown, CaretLeft, CaretRight, CaretUp, CheckCircle, CircleNotch, Clock, Cpu, Gauge, Info, LockKey, Engine, Play, Power, SlidersHorizontal, Speedometer, StopCircle, TerminalWindow, Thermometer, Warning, WifiHigh } from "@phosphor-icons/react";

const API="/api", CLIENT_ID=`webui-${Math.random().toString(16).slice(2,8)}`;
const initial={service_online:false,simulation:true,can_interface:"can0",can_state:"unknown",control:{owned:false},drive:{enabled:false,emergency_stop:false,linear_m_s:0,angular_rad_s:0},motors:{left:{id:1,online:false,velocity_rad_s:0,bus_voltage_v:0,motor_temperature_c:0},right:{id:2,online:false,velocity_rad_s:0,bus_voltage_v:0,motor_temperature_c:0}},updated_at:"--"};
async function api(path,options={}){const r=await fetch(`${API}${path}`,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`请求失败 (${r.status})`);return p}
function NavItem({icon:Icon,label,active}){return <button className={`nav-item ${active?"active":""}`}><Icon size={23} weight={active?"duotone":"regular"}/><span>{label}</span></button>}
function StatusLine({children,tone="cyan"}){return <span className={`status-line ${tone}`}><i/>{children}</span>}
function DataRow({icon:Icon,label,left,right,suffix=""}){return <div className="data-row"><div className="row-label"><Icon size={24}/><span>{label}</span></div><strong>{left}{suffix}</strong><strong>{right}{suffix}</strong></div>}
function Joystick({disabled,onVector,onEngage,onRelease}){const ref=useRef(null);const [knob,setKnob]=useState({x:0,y:0});const move=useCallback(e=>{if(disabled||!ref.current)return;const rect=ref.current.getBoundingClientRect(),radius=rect.width/2-30;let x=e.clientX-(rect.left+rect.width/2),y=e.clientY-(rect.top+rect.height/2),d=Math.hypot(x,y);if(d>radius){x*=radius/d;y*=radius/d}setKnob({x,y});onVector({linear:Math.max(-1,Math.min(1,-y/radius)),angular:Math.max(-1,Math.min(1,x/radius))})},[disabled,onVector]);const release=useCallback(e=>{if(ref.current?.hasPointerCapture(e.pointerId))ref.current.releasePointerCapture(e.pointerId);setKnob({x:0,y:0});onRelease()},[onRelease]);return <div ref={ref} className={`joystick ${disabled?"disabled":""}`} role="slider" aria-label="底盘速度摇杆" aria-disabled={disabled} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);onEngage();move(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))move(e)}} onPointerUp={release} onPointerCancel={release}><span className="cross x"/><span className="cross y"/><span className="circle c1"/><span className="circle c2"/><b className="dir n">前进<small>+0.60 m/s</small></b><b className="dir s">后退<small>-0.60 m/s</small></b><b className="dir w">左转<small>-2.0 rad/s</small></b><b className="dir e">右转<small>+2.0 rad/s</small></b><CaretUp className="arrow a-n"/><CaretDown className="arrow a-s"/><CaretLeft className="arrow a-w"/><CaretRight className="arrow a-e"/><div className="knob" style={{transform:`translate(${knob.x}px,${knob.y}px)`}}><span/></div></div>}

export function App(){
 const [state,setState]=useState(initial),[events,setEvents]=useState([]),[token,setToken]=useState(()=>sessionStorage.getItem("chassis-token")||""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [vector,setVector]=useState({linear:0,angular:0}),[deadman,setDeadman]=useState(false);const keyRef=useRef(new Set()),engageRef=useRef(0),vectorRef=useRef({linear:0,angular:0}),deadmanRef=useRef(false);
 const refresh=useCallback(async()=>{try{setState(await api("/state",{headers:token?{"X-Control-Token":token}:{}}));setError("")}catch(e){setState(s=>({...s,service_online:false,can_state:"disconnected"}));setError(e.message)}},[token]);
 const refreshEvents=useCallback(async()=>{try{setEvents((await api("/events")).events||[])}catch{}},[]);
 useEffect(()=>{refresh();refreshEvents();const a=setInterval(refresh,500),b=setInterval(refreshEvents,1500);return()=>{clearInterval(a);clearInterval(b)}},[refresh,refreshEvents]);
 const act=async fn=>{setBusy(true);setError("");try{await fn();await refresh();await refreshEvents()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const acquire=()=>act(async()=>{const p=await api("/control/acquire",{method:"POST",body:JSON.stringify({owner:CLIENT_ID})});sessionStorage.setItem("chassis-token",p.token);setToken(p.token)});
 const release=()=>act(async()=>{await api("/control/release",{method:"POST",body:JSON.stringify({token})});sessionStorage.removeItem("chassis-token");setToken("")});
 const postVector=useCallback(async v=>api("/drive/command",{method:"POST",body:JSON.stringify({token,linear:v.linear*.6,angular:v.angular*2})}),[token]);
 const send=useCallback(async v=>{vectorRef.current=v;setVector(v);if(!token||!deadmanRef.current||state.drive.emergency_stop)return;try{await postVector(v)}catch(e){setError(e.message)}},[token,state.drive.emergency_stop,postVector]);
 const stop=useCallback(async()=>{const zero={linear:0,angular:0};vectorRef.current=zero;setVector(zero);if(token)try{await api("/drive/stop",{method:"POST",body:JSON.stringify({token})})}catch(e){setError(e.message)}},[token]);
 const deadmanStart=async()=>{if(!token||state.drive.emergency_stop||deadmanRef.current)return;const generation=++engageRef.current;try{await api("/drive/enable",{method:"POST",body:JSON.stringify({token})});if(engageRef.current!==generation)return;deadmanRef.current=true;setDeadman(true);await postVector(vectorRef.current)}catch(e){if(engageRef.current===generation){deadmanRef.current=false;setDeadman(false)}setError(e.message)}};
 const deadmanStop=useCallback(async()=>{engageRef.current+=1;deadmanRef.current=false;setDeadman(false);if(token)try{await api("/drive/disable",{method:"POST",body:JSON.stringify({token})})}catch(e){setError(e.message)}},[token]);
 const joystickRelease=useCallback(async()=>{await stop();await deadmanStop()},[stop,deadmanStop]);
 useEffect(()=>{if(!deadman||!token)return;const t=setInterval(()=>postVector(vectorRef.current).catch(e=>setError(e.message)),100);return()=>clearInterval(t)},[deadman,token,postVector]);
 useEffect(()=>{const get=()=>({linear:(keyRef.current.has("w")||keyRef.current.has("arrowup")?1:0)-(keyRef.current.has("s")||keyRef.current.has("arrowdown")?1:0),angular:(keyRef.current.has("d")||keyRef.current.has("arrowright")?1:0)-(keyRef.current.has("a")||keyRef.current.has("arrowleft")?1:0)});const down=e=>{const k=e.key.toLowerCase();if(k===" "){e.preventDefault();if(!deadman)deadmanStart();return}if(!["w","a","s","d","arrowup","arrowdown","arrowleft","arrowright"].includes(k))return;e.preventDefault();keyRef.current.add(k);send(get())};const up=e=>{const k=e.key.toLowerCase();if(k===" "){deadmanStop();return}keyRef.current.delete(k);send(get())};addEventListener("keydown",down);addEventListener("keyup",up);addEventListener("blur",deadmanStop);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up);removeEventListener("blur",deadmanStop)}},[deadman,send,deadmanStop]);
 const owned=Boolean(token&&state.control.owned),ready=owned&&!state.drive.emergency_stop,left=state.motors.left,right=state.motors.right;
 const linear=Number(state.drive.linear_m_s||0).toFixed(2),angular=Number(state.drive.angular_rad_s||0).toFixed(2);
 return <div className="shell"><aside><div className="side-title">底盘调试台</div><nav><NavItem icon={Gauge} label="驾驶台" active/><NavItem icon={Engine} label="电机"/><NavItem icon={SlidersHorizontal} label="参数"/><NavItem icon={TerminalWindow} label="日志"/></nav><div className="side-clock"><Clock size={24}/><span>{new Date().toLocaleDateString("zh-CN")}<small>{state.updated_at}</small></span></div></aside>
 <main><header><StatusLine tone="green">服务在线</StatusLine><span className="separator"/><StatusLine>CAN0 · 1 Mbps</StatusLine><span className="separator"/><button className={`control-lock ${owned?"owned":""}`} onClick={owned?release:acquire} disabled={busy||!state.service_online}>{busy?<CircleNotch className="spin"/>:<LockKey size={25}/>} {owned?"控制权已锁定":"取得控制权"}</button><button className="estop" onClick={()=>act(()=>api("/drive/emergency-stop",{method:"POST",body:"{}"}))}><StopCircle size={31} weight="bold"/>急停</button></header>
 {error&&<div className="error"><Warning size={18}/>{error}<button onClick={()=>setError("")}>关闭</button></div>}
 {state.drive.emergency_stop&&<div className="error"><StopCircle size={18}/>急停已锁定，电机输出被禁止。<button disabled={!owned} onClick={()=>act(()=>api("/drive/reset-emergency",{method:"POST",body:JSON.stringify({token})}))}>确认安全并复位</button></div>}
 <div className="notice"><Info size={18}/><span>首次或重新上电后，请先取得控制权并按住启用；松开立即失能。</span><small>实时刷新：500 ms <i/></small></div>
 <section className="console-grid"><article className="control-card"><div className="control-main"><Joystick disabled={!ready} onVector={send} onEngage={deadmanStart} onRelease={joystickRelease}/><div className="command-readout"><div className="readout"><label>线速度 <span>(m/s)</span></label><strong>{linear}</strong><small>范围 -0.60 ～ +0.60</small><div className="ticks"/></div><div className="readout"><label>角速度 <span>(rad/s)</span></label><strong>{angular}</strong><small>范围 -2.00 ～ +2.00</small><div className="ticks"/></div></div></div>
 <div className="deadman-row"><button className={`deadman ${deadman?"pressed":""}`} disabled={!ready} onPointerDown={deadmanStart} onPointerUp={deadmanStop} onPointerCancel={deadmanStop}><LockKey size={28}/><strong>{deadman?"保持启用":"按住启用"}</strong></button><div className="short-test"><label>短时测试 <span>(上限 30 s)</span></label><strong>00:00 <span>/ 30 s</span></strong><button disabled><Play size={20}/>开始测试</button></div></div>
 <div className="warning"><Warning size={18} weight="fill"/>{ready?"已取得控制权，按住空格或启用按钮后才发送运动指令。":"未使能：控制已禁止，移动指令不会发送到电机。"}</div></article>
 <article className="motor-card"><div className="card-head"><h2>电机状态</h2><small>实时刷新：500 ms <i/></small></div><div className="table-head"><span>项目</span><strong>左轮 0x01</strong><strong>右轮 0x02</strong></div><DataRow icon={Thermometer} label="温度" left={left.motor_temperature_c.toFixed(1)} right={right.motor_temperature_c.toFixed(1)} suffix=" °C"/><DataRow icon={BatteryCharging} label="电压" left={left.bus_voltage_v.toFixed(1)} right={right.bus_voltage_v.toFixed(1)} suffix=" V"/><DataRow icon={Speedometer} label="目标转速" left={left.velocity_rad_s.toFixed(1)} right={right.velocity_rad_s.toFixed(1)} suffix=" rad/s"/><DataRow icon={SlidersHorizontal} label="模式" left="速度模式" right="速度模式"/><DataRow icon={WifiHigh} label="在线状态" left={<span className={left.online?"online":"offline"}><CheckCircle weight="fill"/> {left.online?"在线":"离线"}</span>} right={<span className={right.online?"online":"offline"}><CheckCircle weight="fill"/> {right.online?"在线":"离线"}</span>}/></article></section>
 <article className="log-card"><div className="log-head"><h2>实时事件</h2><span>显示最新 {Math.min(events.length,50)} 条</span></div>{events.slice(0,5).map((ev,i)=><div className="log-row" key={`${ev.time}-${i}`}><time>{ev.time}</time><b className={ev.level}>{ev.level.toUpperCase()}</b><span>{ev.message}</span><CaretDown size={17}/></div>)}{!events.length&&<div className="log-row empty">暂无事件</div>}</article>
 <footer>{state.simulation?"模拟模式 · 不会驱动真实电机":`${state.can_interface} · 实机模式`}<span>控制看门狗 750 ms</span></footer></main></div>
}





